// Code generated by protoc-gen-go.
// source: bi.proto
// DO NOT EDIT!

/*
Package p is a generated protocol buffer package.

It is generated from these files:
	bi.proto

It has these top-level messages:
	BiLog
	BiResult
*/
package p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type BiLog struct {
	ProjectName string `protobuf:"bytes,1,opt,name=projectName" json:"projectName,omitempty"`
	ActionName  string `protobuf:"bytes,2,opt,name=actionName" json:"actionName,omitempty"`
	Timestamp   int64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Detail      []byte `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (m *BiLog) Reset()                    { *m = BiLog{} }
func (m *BiLog) String() string            { return proto.CompactTextString(m) }
func (*BiLog) ProtoMessage()               {}
func (*BiLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BiResult struct {
	Result bool   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *BiResult) Reset()                    { *m = BiResult{} }
func (m *BiResult) String() string            { return proto.CompactTextString(m) }
func (*BiResult) ProtoMessage()               {}
func (*BiResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*BiLog)(nil), "p.BiLog")
	proto.RegisterType((*BiResult)(nil), "p.BiResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for MisBi service

type MisBiClient interface {
	Bi(ctx context.Context, in *BiLog, opts ...grpc.CallOption) (*BiResult, error)
}

type misBiClient struct {
	cc *grpc.ClientConn
}

func NewMisBiClient(cc *grpc.ClientConn) MisBiClient {
	return &misBiClient{cc}
}

func (c *misBiClient) Bi(ctx context.Context, in *BiLog, opts ...grpc.CallOption) (*BiResult, error) {
	out := new(BiResult)
	err := grpc.Invoke(ctx, "/p.MisBi/Bi", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MisBi service

type MisBiServer interface {
	Bi(context.Context, *BiLog) (*BiResult, error)
}

func RegisterMisBiServer(s *grpc.Server, srv MisBiServer) {
	s.RegisterService(&_MisBi_serviceDesc, srv)
}

func _MisBi_Bi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MisBiServer).Bi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p.MisBi/Bi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MisBiServer).Bi(ctx, req.(*BiLog))
	}
	return interceptor(ctx, in, info, handler)
}

var _MisBi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "p.MisBi",
	HandlerType: (*MisBiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bi",
			Handler:    _MisBi_Bi_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4f, 0x03, 0x21,
	0x10, 0x85, 0xdd, 0xae, 0xad, 0x74, 0xea, 0xc1, 0x70, 0x30, 0x9b, 0x46, 0x4d, 0xb3, 0x07, 0xf5,
	0xc4, 0x41, 0xfd, 0x05, 0x9c, 0xd5, 0x34, 0xfc, 0x03, 0x8a, 0x84, 0x8c, 0x59, 0x16, 0x02, 0xd3,
	0xb3, 0x7f, 0x5d, 0x16, 0x37, 0x71, 0x2f, 0xe4, 0xcd, 0x37, 0x2f, 0xbc, 0xcc, 0x03, 0x76, 0x42,
	0x11, 0x53, 0xa0, 0xc0, 0x9b, 0xd8, 0xff, 0xc0, 0x5a, 0xe2, 0x7b, 0x70, 0xfc, 0x00, 0xbb, 0x02,
	0xbf, 0xad, 0xa1, 0x4f, 0xed, 0x6d, 0xd7, 0x1c, 0x9a, 0xe7, 0xad, 0x5a, 0x22, 0xfe, 0x00, 0xa0,
	0x0d, 0x61, 0x18, 0xab, 0x61, 0x55, 0x0d, 0x0b, 0xc2, 0xef, 0x60, 0x4b, 0xe8, 0x6d, 0x26, 0xed,
	0x63, 0xd7, 0x96, 0x75, 0xab, 0xfe, 0x01, 0xbf, 0x85, 0xcd, 0x97, 0x25, 0x8d, 0x43, 0x77, 0x59,
	0x56, 0xd7, 0x6a, 0x9e, 0xfa, 0x37, 0x60, 0x12, 0x95, 0xcd, 0xe7, 0x81, 0x26, 0x4f, 0xaa, 0xaa,
	0xc6, 0x33, 0x35, 0x4f, 0xfc, 0x06, 0x5a, 0x9f, 0xdd, 0x1c, 0x39, 0xc9, 0x97, 0x47, 0x58, 0x7f,
	0x60, 0x96, 0xc8, 0xef, 0x61, 0x55, 0x5e, 0x26, 0xa2, 0xa8, 0x67, 0xec, 0x77, 0x55, 0xfd, 0xfd,
	0xd7, 0x5f, 0xc8, 0x27, 0xd8, 0x9b, 0xe0, 0x45, 0xc6, 0xd1, 0x9d, 0x07, 0x9d, 0x62, 0xc0, 0x91,
	0xb2, 0xc0, 0x20, 0x5c, 0x8a, 0x46, 0x5e, 0x49, 0x3c, 0x4e, 0x45, 0x1c, 0x9b, 0xd3, 0xa6, 0x36,
	0xf2, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x71, 0x9e, 0xe9, 0x1d, 0x01, 0x00, 0x00,
}
