// Code generated by protoc-gen-go.
// source: bi.proto
// DO NOT EDIT!

/*
Package p is a generated protocol buffer package.

It is generated from these files:
	bi.proto
	deepsharebi.proto

It has these top-level messages:
	BiLog
	BiLogs
*/
package p

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BiLog struct {
	ProjectName      *string                   `protobuf:"bytes,1,req,name=projectName" json:"projectName,omitempty"`
	ActionName       *string                   `protobuf:"bytes,2,opt,name=actionName" json:"actionName,omitempty"`
	Timestamp        *int64                    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *BiLog) Reset()         { *m = BiLog{} }
func (m *BiLog) String() string { return proto.CompactTextString(m) }
func (*BiLog) ProtoMessage()    {}

var extRange_BiLog = []proto.ExtensionRange{
	{100, 199},
}

func (*BiLog) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_BiLog
}
func (m *BiLog) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *BiLog) GetProjectName() string {
	if m != nil && m.ProjectName != nil {
		return *m.ProjectName
	}
	return ""
}

func (m *BiLog) GetActionName() string {
	if m != nil && m.ActionName != nil {
		return *m.ActionName
	}
	return ""
}

func (m *BiLog) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type BiLogs struct {
	ProjectName      *string  `protobuf:"bytes,1,req,name=projectName" json:"projectName,omitempty"`
	FromTime         *int64   `protobuf:"varint,2,opt,name=fromTime" json:"fromTime,omitempty"`
	ToTime           *int64   `protobuf:"varint,3,opt,name=toTime" json:"toTime,omitempty"`
	Logs             []*BiLog `protobuf:"bytes,4,rep,name=logs" json:"logs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BiLogs) Reset()         { *m = BiLogs{} }
func (m *BiLogs) String() string { return proto.CompactTextString(m) }
func (*BiLogs) ProtoMessage()    {}

func (m *BiLogs) GetProjectName() string {
	if m != nil && m.ProjectName != nil {
		return *m.ProjectName
	}
	return ""
}

func (m *BiLogs) GetFromTime() int64 {
	if m != nil && m.FromTime != nil {
		return *m.FromTime
	}
	return 0
}

func (m *BiLogs) GetToTime() int64 {
	if m != nil && m.ToTime != nil {
		return *m.ToTime
	}
	return 0
}

func (m *BiLogs) GetLogs() []*BiLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
}
