// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

public interface BiLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.BiLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string projectName = 1;</code>
   */
  java.lang.String getProjectName();
  /**
   * <code>optional string projectName = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectNameBytes();

  /**
   * <code>optional string actionName = 2;</code>
   */
  java.lang.String getActionName();
  /**
   * <code>optional string actionName = 2;</code>
   */
  com.google.protobuf.ByteString
      getActionNameBytes();

  /**
   * <code>optional int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>optional bytes detail = 4;</code>
   */
  com.google.protobuf.ByteString getDetail();
}
