// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

public interface BiResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.BiResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>optional string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
