// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

/**
 * Protobuf type {@code p.CommandExecutePerformance}
 */
public  final class CommandExecutePerformance extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:p.CommandExecutePerformance)
    CommandExecutePerformanceOrBuilder {
  // Use CommandExecutePerformance.newBuilder() to construct.
  private CommandExecutePerformance(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommandExecutePerformance() {
    speakTime_ = 0L;
    receiveVoiceResultTime_ = 0L;
    sendCommandTime_ = 0L;
    receiveResultTime_ = 0L;
    commandText_ = "";
    queryId_ = "";
    deviceId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CommandExecutePerformance(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            speakTime_ = input.readInt64();
            break;
          }
          case 16: {

            receiveVoiceResultTime_ = input.readInt64();
            break;
          }
          case 24: {

            sendCommandTime_ = input.readInt64();
            break;
          }
          case 32: {

            receiveResultTime_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            commandText_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            queryId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.singulariti.io.grpc.BiProto.internal_static_p_CommandExecutePerformance_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.singulariti.io.grpc.BiProto.internal_static_p_CommandExecutePerformance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.singulariti.io.grpc.CommandExecutePerformance.class, com.singulariti.io.grpc.CommandExecutePerformance.Builder.class);
  }

  public static final int SPEAK_TIME_FIELD_NUMBER = 1;
  private long speakTime_;
  /**
   * <code>optional int64 speak_time = 1;</code>
   */
  public long getSpeakTime() {
    return speakTime_;
  }

  public static final int RECEIVE_VOICE_RESULT_TIME_FIELD_NUMBER = 2;
  private long receiveVoiceResultTime_;
  /**
   * <code>optional int64 receive_voice_result_time = 2;</code>
   */
  public long getReceiveVoiceResultTime() {
    return receiveVoiceResultTime_;
  }

  public static final int SEND_COMMAND_TIME_FIELD_NUMBER = 3;
  private long sendCommandTime_;
  /**
   * <code>optional int64 send_command_time = 3;</code>
   */
  public long getSendCommandTime() {
    return sendCommandTime_;
  }

  public static final int RECEIVE_RESULT_TIME_FIELD_NUMBER = 4;
  private long receiveResultTime_;
  /**
   * <code>optional int64 receive_result_time = 4;</code>
   */
  public long getReceiveResultTime() {
    return receiveResultTime_;
  }

  public static final int COMMAND_TEXT_FIELD_NUMBER = 5;
  private volatile java.lang.Object commandText_;
  /**
   * <code>optional string command_text = 5;</code>
   */
  public java.lang.String getCommandText() {
    java.lang.Object ref = commandText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandText_ = s;
      return s;
    }
  }
  /**
   * <code>optional string command_text = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCommandTextBytes() {
    java.lang.Object ref = commandText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERY_ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object queryId_;
  /**
   * <code>optional string query_id = 6;</code>
   */
  public java.lang.String getQueryId() {
    java.lang.Object ref = queryId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queryId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string query_id = 6;</code>
   */
  public com.google.protobuf.ByteString
      getQueryIdBytes() {
    java.lang.Object ref = queryId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queryId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 7;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>optional string device_id = 7;</code>
   */
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string device_id = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (speakTime_ != 0L) {
      output.writeInt64(1, speakTime_);
    }
    if (receiveVoiceResultTime_ != 0L) {
      output.writeInt64(2, receiveVoiceResultTime_);
    }
    if (sendCommandTime_ != 0L) {
      output.writeInt64(3, sendCommandTime_);
    }
    if (receiveResultTime_ != 0L) {
      output.writeInt64(4, receiveResultTime_);
    }
    if (!getCommandTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, commandText_);
    }
    if (!getQueryIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, queryId_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, deviceId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (speakTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, speakTime_);
    }
    if (receiveVoiceResultTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, receiveVoiceResultTime_);
    }
    if (sendCommandTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, sendCommandTime_);
    }
    if (receiveResultTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, receiveResultTime_);
    }
    if (!getCommandTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, commandText_);
    }
    if (!getQueryIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, queryId_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, deviceId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.singulariti.io.grpc.CommandExecutePerformance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.singulariti.io.grpc.CommandExecutePerformance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code p.CommandExecutePerformance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:p.CommandExecutePerformance)
      com.singulariti.io.grpc.CommandExecutePerformanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.singulariti.io.grpc.BiProto.internal_static_p_CommandExecutePerformance_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.singulariti.io.grpc.BiProto.internal_static_p_CommandExecutePerformance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.singulariti.io.grpc.CommandExecutePerformance.class, com.singulariti.io.grpc.CommandExecutePerformance.Builder.class);
    }

    // Construct using com.singulariti.io.grpc.CommandExecutePerformance.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      speakTime_ = 0L;

      receiveVoiceResultTime_ = 0L;

      sendCommandTime_ = 0L;

      receiveResultTime_ = 0L;

      commandText_ = "";

      queryId_ = "";

      deviceId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.singulariti.io.grpc.BiProto.internal_static_p_CommandExecutePerformance_descriptor;
    }

    public com.singulariti.io.grpc.CommandExecutePerformance getDefaultInstanceForType() {
      return com.singulariti.io.grpc.CommandExecutePerformance.getDefaultInstance();
    }

    public com.singulariti.io.grpc.CommandExecutePerformance build() {
      com.singulariti.io.grpc.CommandExecutePerformance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.singulariti.io.grpc.CommandExecutePerformance buildPartial() {
      com.singulariti.io.grpc.CommandExecutePerformance result = new com.singulariti.io.grpc.CommandExecutePerformance(this);
      result.speakTime_ = speakTime_;
      result.receiveVoiceResultTime_ = receiveVoiceResultTime_;
      result.sendCommandTime_ = sendCommandTime_;
      result.receiveResultTime_ = receiveResultTime_;
      result.commandText_ = commandText_;
      result.queryId_ = queryId_;
      result.deviceId_ = deviceId_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.singulariti.io.grpc.CommandExecutePerformance) {
        return mergeFrom((com.singulariti.io.grpc.CommandExecutePerformance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.singulariti.io.grpc.CommandExecutePerformance other) {
      if (other == com.singulariti.io.grpc.CommandExecutePerformance.getDefaultInstance()) return this;
      if (other.getSpeakTime() != 0L) {
        setSpeakTime(other.getSpeakTime());
      }
      if (other.getReceiveVoiceResultTime() != 0L) {
        setReceiveVoiceResultTime(other.getReceiveVoiceResultTime());
      }
      if (other.getSendCommandTime() != 0L) {
        setSendCommandTime(other.getSendCommandTime());
      }
      if (other.getReceiveResultTime() != 0L) {
        setReceiveResultTime(other.getReceiveResultTime());
      }
      if (!other.getCommandText().isEmpty()) {
        commandText_ = other.commandText_;
        onChanged();
      }
      if (!other.getQueryId().isEmpty()) {
        queryId_ = other.queryId_;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.singulariti.io.grpc.CommandExecutePerformance parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.singulariti.io.grpc.CommandExecutePerformance) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long speakTime_ ;
    /**
     * <code>optional int64 speak_time = 1;</code>
     */
    public long getSpeakTime() {
      return speakTime_;
    }
    /**
     * <code>optional int64 speak_time = 1;</code>
     */
    public Builder setSpeakTime(long value) {
      
      speakTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 speak_time = 1;</code>
     */
    public Builder clearSpeakTime() {
      
      speakTime_ = 0L;
      onChanged();
      return this;
    }

    private long receiveVoiceResultTime_ ;
    /**
     * <code>optional int64 receive_voice_result_time = 2;</code>
     */
    public long getReceiveVoiceResultTime() {
      return receiveVoiceResultTime_;
    }
    /**
     * <code>optional int64 receive_voice_result_time = 2;</code>
     */
    public Builder setReceiveVoiceResultTime(long value) {
      
      receiveVoiceResultTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 receive_voice_result_time = 2;</code>
     */
    public Builder clearReceiveVoiceResultTime() {
      
      receiveVoiceResultTime_ = 0L;
      onChanged();
      return this;
    }

    private long sendCommandTime_ ;
    /**
     * <code>optional int64 send_command_time = 3;</code>
     */
    public long getSendCommandTime() {
      return sendCommandTime_;
    }
    /**
     * <code>optional int64 send_command_time = 3;</code>
     */
    public Builder setSendCommandTime(long value) {
      
      sendCommandTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 send_command_time = 3;</code>
     */
    public Builder clearSendCommandTime() {
      
      sendCommandTime_ = 0L;
      onChanged();
      return this;
    }

    private long receiveResultTime_ ;
    /**
     * <code>optional int64 receive_result_time = 4;</code>
     */
    public long getReceiveResultTime() {
      return receiveResultTime_;
    }
    /**
     * <code>optional int64 receive_result_time = 4;</code>
     */
    public Builder setReceiveResultTime(long value) {
      
      receiveResultTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 receive_result_time = 4;</code>
     */
    public Builder clearReceiveResultTime() {
      
      receiveResultTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object commandText_ = "";
    /**
     * <code>optional string command_text = 5;</code>
     */
    public java.lang.String getCommandText() {
      java.lang.Object ref = commandText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string command_text = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommandTextBytes() {
      java.lang.Object ref = commandText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string command_text = 5;</code>
     */
    public Builder setCommandText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commandText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string command_text = 5;</code>
     */
    public Builder clearCommandText() {
      
      commandText_ = getDefaultInstance().getCommandText();
      onChanged();
      return this;
    }
    /**
     * <code>optional string command_text = 5;</code>
     */
    public Builder setCommandTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commandText_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object queryId_ = "";
    /**
     * <code>optional string query_id = 6;</code>
     */
    public java.lang.String getQueryId() {
      java.lang.Object ref = queryId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queryId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string query_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getQueryIdBytes() {
      java.lang.Object ref = queryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string query_id = 6;</code>
     */
    public Builder setQueryId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      queryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string query_id = 6;</code>
     */
    public Builder clearQueryId() {
      
      queryId_ = getDefaultInstance().getQueryId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string query_id = 6;</code>
     */
    public Builder setQueryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      queryId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>optional string device_id = 7;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string device_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string device_id = 7;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string device_id = 7;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string device_id = 7;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:p.CommandExecutePerformance)
  }

  // @@protoc_insertion_point(class_scope:p.CommandExecutePerformance)
  private static final com.singulariti.io.grpc.CommandExecutePerformance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.singulariti.io.grpc.CommandExecutePerformance();
  }

  public static com.singulariti.io.grpc.CommandExecutePerformance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandExecutePerformance>
      PARSER = new com.google.protobuf.AbstractParser<CommandExecutePerformance>() {
    public CommandExecutePerformance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new CommandExecutePerformance(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<CommandExecutePerformance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandExecutePerformance> getParserForType() {
    return PARSER;
  }

  public com.singulariti.io.grpc.CommandExecutePerformance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

