// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

public interface CommandResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.CommandResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string command_name = 1;</code>
   */
  java.lang.String getCommandName();
  /**
   * <code>optional string command_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommandNameBytes();

  /**
   * <code>optional string query_id = 2;</code>
   */
  java.lang.String getQueryId();
  /**
   * <code>optional string query_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getQueryIdBytes();

  /**
   * <code>optional bool use_search_result = 3;</code>
   */
  boolean getUseSearchResult();

  /**
   * <code>optional bool user_choose_trigger = 4;</code>
   *
   * <pre>
   *whether user thinks this is the right result
   * </pre>
   */
  boolean getUserChooseTrigger();

  /**
   * <code>optional int64 date_time = 5;</code>
   *
   * <pre>
   *uses to analyse how many times user trigger this app per day,what is the interval
   * </pre>
   */
  long getDateTime();
}
