// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

/**
 * Protobuf type {@code p.CommandResult}
 */
public  final class CommandResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:p.CommandResult)
    CommandResultOrBuilder {
  // Use CommandResult.newBuilder() to construct.
  private CommandResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommandResult() {
    commandName_ = "";
    queryId_ = "";
    useSearchResult_ = false;
    userChooseTrigger_ = false;
    dateTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CommandResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            commandName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            queryId_ = s;
            break;
          }
          case 24: {

            useSearchResult_ = input.readBool();
            break;
          }
          case 32: {

            userChooseTrigger_ = input.readBool();
            break;
          }
          case 40: {

            dateTime_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.singulariti.io.grpc.BiProto.internal_static_p_CommandResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.singulariti.io.grpc.BiProto.internal_static_p_CommandResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.singulariti.io.grpc.CommandResult.class, com.singulariti.io.grpc.CommandResult.Builder.class);
  }

  public static final int COMMAND_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object commandName_;
  /**
   * <code>optional string command_name = 1;</code>
   */
  public java.lang.String getCommandName() {
    java.lang.Object ref = commandName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string command_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCommandNameBytes() {
    java.lang.Object ref = commandName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERY_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object queryId_;
  /**
   * <code>optional string query_id = 2;</code>
   */
  public java.lang.String getQueryId() {
    java.lang.Object ref = queryId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queryId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string query_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getQueryIdBytes() {
    java.lang.Object ref = queryId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queryId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USE_SEARCH_RESULT_FIELD_NUMBER = 3;
  private boolean useSearchResult_;
  /**
   * <code>optional bool use_search_result = 3;</code>
   */
  public boolean getUseSearchResult() {
    return useSearchResult_;
  }

  public static final int USER_CHOOSE_TRIGGER_FIELD_NUMBER = 4;
  private boolean userChooseTrigger_;
  /**
   * <code>optional bool user_choose_trigger = 4;</code>
   *
   * <pre>
   *whether user thinks this is the right result
   * </pre>
   */
  public boolean getUserChooseTrigger() {
    return userChooseTrigger_;
  }

  public static final int DATE_TIME_FIELD_NUMBER = 5;
  private long dateTime_;
  /**
   * <code>optional int64 date_time = 5;</code>
   *
   * <pre>
   *uses to analyse how many times user trigger this app per day,what is the interval
   * </pre>
   */
  public long getDateTime() {
    return dateTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCommandNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, commandName_);
    }
    if (!getQueryIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, queryId_);
    }
    if (useSearchResult_ != false) {
      output.writeBool(3, useSearchResult_);
    }
    if (userChooseTrigger_ != false) {
      output.writeBool(4, userChooseTrigger_);
    }
    if (dateTime_ != 0L) {
      output.writeInt64(5, dateTime_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCommandNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, commandName_);
    }
    if (!getQueryIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, queryId_);
    }
    if (useSearchResult_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, useSearchResult_);
    }
    if (userChooseTrigger_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, userChooseTrigger_);
    }
    if (dateTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, dateTime_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.singulariti.io.grpc.CommandResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.singulariti.io.grpc.CommandResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.singulariti.io.grpc.CommandResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.singulariti.io.grpc.CommandResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.singulariti.io.grpc.CommandResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.singulariti.io.grpc.CommandResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.singulariti.io.grpc.CommandResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.singulariti.io.grpc.CommandResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code p.CommandResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:p.CommandResult)
      com.singulariti.io.grpc.CommandResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.singulariti.io.grpc.BiProto.internal_static_p_CommandResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.singulariti.io.grpc.BiProto.internal_static_p_CommandResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.singulariti.io.grpc.CommandResult.class, com.singulariti.io.grpc.CommandResult.Builder.class);
    }

    // Construct using com.singulariti.io.grpc.CommandResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      commandName_ = "";

      queryId_ = "";

      useSearchResult_ = false;

      userChooseTrigger_ = false;

      dateTime_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.singulariti.io.grpc.BiProto.internal_static_p_CommandResult_descriptor;
    }

    public com.singulariti.io.grpc.CommandResult getDefaultInstanceForType() {
      return com.singulariti.io.grpc.CommandResult.getDefaultInstance();
    }

    public com.singulariti.io.grpc.CommandResult build() {
      com.singulariti.io.grpc.CommandResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.singulariti.io.grpc.CommandResult buildPartial() {
      com.singulariti.io.grpc.CommandResult result = new com.singulariti.io.grpc.CommandResult(this);
      result.commandName_ = commandName_;
      result.queryId_ = queryId_;
      result.useSearchResult_ = useSearchResult_;
      result.userChooseTrigger_ = userChooseTrigger_;
      result.dateTime_ = dateTime_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.singulariti.io.grpc.CommandResult) {
        return mergeFrom((com.singulariti.io.grpc.CommandResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.singulariti.io.grpc.CommandResult other) {
      if (other == com.singulariti.io.grpc.CommandResult.getDefaultInstance()) return this;
      if (!other.getCommandName().isEmpty()) {
        commandName_ = other.commandName_;
        onChanged();
      }
      if (!other.getQueryId().isEmpty()) {
        queryId_ = other.queryId_;
        onChanged();
      }
      if (other.getUseSearchResult() != false) {
        setUseSearchResult(other.getUseSearchResult());
      }
      if (other.getUserChooseTrigger() != false) {
        setUserChooseTrigger(other.getUserChooseTrigger());
      }
      if (other.getDateTime() != 0L) {
        setDateTime(other.getDateTime());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.singulariti.io.grpc.CommandResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.singulariti.io.grpc.CommandResult) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object commandName_ = "";
    /**
     * <code>optional string command_name = 1;</code>
     */
    public java.lang.String getCommandName() {
      java.lang.Object ref = commandName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string command_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommandNameBytes() {
      java.lang.Object ref = commandName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string command_name = 1;</code>
     */
    public Builder setCommandName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commandName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string command_name = 1;</code>
     */
    public Builder clearCommandName() {
      
      commandName_ = getDefaultInstance().getCommandName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string command_name = 1;</code>
     */
    public Builder setCommandNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commandName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object queryId_ = "";
    /**
     * <code>optional string query_id = 2;</code>
     */
    public java.lang.String getQueryId() {
      java.lang.Object ref = queryId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queryId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string query_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQueryIdBytes() {
      java.lang.Object ref = queryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string query_id = 2;</code>
     */
    public Builder setQueryId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      queryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string query_id = 2;</code>
     */
    public Builder clearQueryId() {
      
      queryId_ = getDefaultInstance().getQueryId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string query_id = 2;</code>
     */
    public Builder setQueryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      queryId_ = value;
      onChanged();
      return this;
    }

    private boolean useSearchResult_ ;
    /**
     * <code>optional bool use_search_result = 3;</code>
     */
    public boolean getUseSearchResult() {
      return useSearchResult_;
    }
    /**
     * <code>optional bool use_search_result = 3;</code>
     */
    public Builder setUseSearchResult(boolean value) {
      
      useSearchResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool use_search_result = 3;</code>
     */
    public Builder clearUseSearchResult() {
      
      useSearchResult_ = false;
      onChanged();
      return this;
    }

    private boolean userChooseTrigger_ ;
    /**
     * <code>optional bool user_choose_trigger = 4;</code>
     *
     * <pre>
     *whether user thinks this is the right result
     * </pre>
     */
    public boolean getUserChooseTrigger() {
      return userChooseTrigger_;
    }
    /**
     * <code>optional bool user_choose_trigger = 4;</code>
     *
     * <pre>
     *whether user thinks this is the right result
     * </pre>
     */
    public Builder setUserChooseTrigger(boolean value) {
      
      userChooseTrigger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool user_choose_trigger = 4;</code>
     *
     * <pre>
     *whether user thinks this is the right result
     * </pre>
     */
    public Builder clearUserChooseTrigger() {
      
      userChooseTrigger_ = false;
      onChanged();
      return this;
    }

    private long dateTime_ ;
    /**
     * <code>optional int64 date_time = 5;</code>
     *
     * <pre>
     *uses to analyse how many times user trigger this app per day,what is the interval
     * </pre>
     */
    public long getDateTime() {
      return dateTime_;
    }
    /**
     * <code>optional int64 date_time = 5;</code>
     *
     * <pre>
     *uses to analyse how many times user trigger this app per day,what is the interval
     * </pre>
     */
    public Builder setDateTime(long value) {
      
      dateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 date_time = 5;</code>
     *
     * <pre>
     *uses to analyse how many times user trigger this app per day,what is the interval
     * </pre>
     */
    public Builder clearDateTime() {
      
      dateTime_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:p.CommandResult)
  }

  // @@protoc_insertion_point(class_scope:p.CommandResult)
  private static final com.singulariti.io.grpc.CommandResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.singulariti.io.grpc.CommandResult();
  }

  public static com.singulariti.io.grpc.CommandResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandResult>
      PARSER = new com.google.protobuf.AbstractParser<CommandResult>() {
    public CommandResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new CommandResult(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<CommandResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandResult> getParserForType() {
    return PARSER;
  }

  public com.singulariti.io.grpc.CommandResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

