// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

public interface CommandExecutePerformanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.CommandExecutePerformance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 speak_time = 1;</code>
   */
  long getSpeakTime();

  /**
   * <code>optional int64 receive_voice_result_time = 2;</code>
   */
  long getReceiveVoiceResultTime();

  /**
   * <code>optional int64 send_command_time = 3;</code>
   */
  long getSendCommandTime();

  /**
   * <code>optional int64 receive_result_time = 4;</code>
   */
  long getReceiveResultTime();

  /**
   * <code>optional string command_text = 5;</code>
   */
  java.lang.String getCommandText();
  /**
   * <code>optional string command_text = 5;</code>
   */
  com.google.protobuf.ByteString
      getCommandTextBytes();

  /**
   * <code>optional string query_id = 6;</code>
   */
  java.lang.String getQueryId();
  /**
   * <code>optional string query_id = 6;</code>
   */
  com.google.protobuf.ByteString
      getQueryIdBytes();

  /**
   * <code>optional string device_id = 7;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>optional string device_id = 7;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();
}
