// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

public interface DeviceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.DeviceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string device_id = 1;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>optional string device_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>optional string manufacturer = 2;</code>
   */
  java.lang.String getManufacturer();
  /**
   * <code>optional string manufacturer = 2;</code>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>optional string model = 3;</code>
   *
   * <pre>
   *uses to analyse what is the most popular manufacturer (for example Huawei) or model (for example, Next 6P)  user uses
   * </pre>
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 3;</code>
   *
   * <pre>
   *uses to analyse what is the most popular manufacturer (for example Huawei) or model (for example, Next 6P)  user uses
   * </pre>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string app_version = 4;</code>
   */
  java.lang.String getAppVersion();
  /**
   * <code>optional string app_version = 4;</code>
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();

  /**
   * <code>optional string ni_version = 5;</code>
   */
  java.lang.String getNiVersion();
  /**
   * <code>optional string ni_version = 5;</code>
   */
  com.google.protobuf.ByteString
      getNiVersionBytes();

  /**
   * <code>optional int64 open_app_time = 6;</code>
   */
  long getOpenAppTime();
}
