// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p/bi.proto

package com.singulariti.io.grpc;

public interface PerformPathIssueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:p.PerformPathIssue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string query_id = 1;</code>
   */
  java.lang.String getQueryId();
  /**
   * <code>optional string query_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryIdBytes();

  /**
   * <code>optional int32 can_perform_path_count = 2;</code>
   */
  int getCanPerformPathCount();
}
